#!/usr/bin/env bash
# This script tells a story based on the content of /etc/passwd

while IFS=":" read -r username _ uid gid info home shell; do
    echo "The user $username is part of the group $gid gang, lives in $home and rides $shell."
    echo -n "User $uid's place is protected by the passcode: "
    grep "^$username:" /etc/shadow | cut -d':' -f2
    echo "More info about the user here: $info"
    echo
done < /etc/passwd

