#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

counter=0

# Loop until counter reaches 10
while [ $counter -lt 10 ]; do
    echo "Best School"
    counter=$((counter + 1))
done
