#!/usr/bin/env bash
# This script checks if the file exists, if it's empty, and if it's a regular file

file="school"

if [ -e "$file" ]; then
    echo "school file exists"
    
    if [ -s "$file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [ -f "$file" ]; then
        echo "school is a regular file"
    else
        :
    fi
else
    echo "school file does not exist"
fi

